# plugin name used to associate data with the plugin
plugin_name = "example"

# Teleport Auth/Proxy address
addr = "localhost:3025"

# Teleport identity file with TLS/SSH certificates.
identity_file = "access-plugin-identity"
