{{- $oldToken := "" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.secretName) -}}
{{- if and $secret $secret.data }}
{{- $oldToken = index ($secret).data "auth-token"}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.extraLabels.secret }}
  labels:
  {{- toYaml .Values.extraLabels.secret | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  auth-token: |
    {{ coalesce .Values.joinParams.tokenName .Values.authToken $oldToken }}
