name: "Lint"

on:
  push:
    branches:
      - master
      - branch/*
  pull_request:
    branches:
      - master
      - branch/*

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-22.04-32core
    container: public.ecr.aws/gravitational/teleport-buildbox:teleport11
    permissions:
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Lint scripts
      run: make lint-sh
      shell: bash
    - name: Lint Helm
      run: make lint-helm
      shell: bash
      if: success() || failure()
    - name: Lint the API
      run: make lint-api
      shell: bash
      if: success() || failure()
    - name: Lint go
      run: make lint-go
      shell: bash
      if: success() || failure()
    - name: Lint license
      run: make lint-license
      shell: bash
      if: success() || failure()
    - name: Lint RDP
      run: make lint-rdp
      shell: bash
      if: success() || failure()

